### ISSUE TITLE
Check if there is possible to reuse symfony cmf routing component

### ISSUE THREAD

**Issue by saimaz** [ongr-io/RouterBundle#8]
https://github.com/symfony-cmf/Routing

**Comment by tautrimas** [comment]
There are too few advantages over using Routing component and bundle.

We can only reuse ChainedRouter instead of default router overriding, but what do we gain?

Instead, we should use http://symfony.com/doc/current/bundles/SensioFrameworkExtraBundle/annotations/converters.html and then only override RouteGenerator.
